### ISSUE TITLE
Can trackControl be exposed?

### ISSUE THREAD

**Issue by dkadrios** [robertsonics/Tsunami-Arduino-Serial-Library#1]
https://github.com/robertsonics/Tsunami-Arduino-Serial-Library/blob/48544e6aa8083950d8139240be5a52180029c19f/Tsunami.h#L119

I'd like to be able to control track routing from an Arduino. (e.g. play track N on a particular output).  Am I correct in thinking that the CONTROL_TRACK message is the only way to do so?  If so, is there any reason why the trackControl() method could not be made public?

**Comment by robertsonics** [comment]
Not sure I understand. trackControl() is just a private method to avoid duplication in many of the commands that control tracks. It doesn't give you any more capability than the public commands. In particular, trackPlaySolo() and trackPlayPoly() include both a track number and an output parameter.

**Comment by dkadrios** [comment]
My mistake,  not sure how I missed that!  Thanks,  Robert.
