### ISSUE TITLE
Track filenames

### ISSUE THREAD

**Issue by qniens** [robertsonics/Tsunami-Arduino-Serial-Library#8]
Hello,
Is it possible to retrieve the filename of a WAV that is on the SD-Card?

Best regards,
Quinten

**Comment by robertsonics** [comment]
Not currently. As I've written in the past, there are several issues with this. First is that while long filenames are possible, I don't currently look beyond the first FAT directory entry and therefore only have access to the first 8 characters of the filename. Secondly, retrieving filenames could be a long operation that could potentially interfere with audio that might happen to be playing. It might be that requesting filenames would necessarily halt audio. Both problems are solvable, but with a fair amount of work.

**Comment by qniens** [comment]
Ok, thank you for the explanation
